name: Sync to Hugging Face hub
on:
  push:
    branches: [prod]

jobs:
    sync-to-hub:
        runs-on: windows-latest

        steps:
        - uses: actions/checkout@v4

        - name: Sync to Hugging Face Hub
            uses: huggingface/hub-sync@v0.1.0
            with:
            github_repo_id: ${{ github.repository }}
            huggingface_repo_id: JPoitreau/OC-Projet-8
            hf_token: ${{ secrets.OC_P8_COMMUNICATE_HF }}
            repo_type: space
            space_sdk: docker